<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pxa_siteimprove"
 *
 * Auto generated by Extension Builder 2018-04-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Siteimprove',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Mattias Nilsson',
    'author_email' => 'mattias@pixelant.se',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
